version: '3'
services:

  #PHP
  app:
    image: gusjara23/laravel-php8.2:latest
    container_name: zenrise
    environment:
      APACHE_RUN_USER: #${UID}
      APACHE_RUN_GROUP: #${UID}
      # VIRTUAL_HOST: ${DOCKER_VIRTUAL_HOST}
      # LETSENCRYPT_HOST: ${DOCKER_VIRTUAL_HOST}
    restart: unless-stopped
    ports: 
      - "8080:80"
    volumes:
      - ./:/var/www/html
      # - ./storage/app/public:/var/www/html/public/storage
      #- ${DOCKER_NFS_PATH}:/var/www/nfs
    networks:
      - webapps-network

#Network
networks:
  webapps-network:
    external: true
    name: webapps-network

#Volumes
volumes:
  dbdata:
    driver: local